name: Coq CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Build Coq project
        uses: coq-community/docker-coq-action@v1
        with:
          coq_version: '8.19'
          script: |
            coqc -q -R COQ StandingAlgebra COQ/StandingAlgebraCoreCoq.v
            coqc -q -R COQ StandingAlgebra COQ/StandingAlgebraBasicsCoq.v
            coqc -q -R COQ StandingAlgebra COQ/StandingAlgebra_Model_Example.v




